# .github/workflows/suggest-go-tests.yml
on:
  pull_request:
    paths:
      - '**/*.go'

jobs:
  suggest-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Suggest Go test cases
        uses: ./
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          github_token:    ${{ secrets.GITHUB_TOKEN }}
